image: python:alpine

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  PIP_CACHE_DIR: "$XDG_CACHE_HOME/pip"
  PRE_COMMIT_HOME: "$XDG_CACHE_HOME/pre-commit"

cache: &global_cache
  key: v1-pip
  paths:
    - ${PIP_CACHE_DIR}

stages:
  - Lint
  - Test
  - Build
  - Publish
  - Release

default:
  before_script: &setup
    - apk add git
    - python --version --version

changelog:
  stage: Lint
  image: alpine:latest
  before_script:
    - apk add git
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - "! git diff --quiet origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME $CI_COMMIT_SHA -- changelog.d/"
  only:
    - merge_requests
  allow_failure: true

pre-commit: &pre-commit
  stage: Lint
  cache:
    - key: v1-pip
      paths:
        - ${PIP_CACHE_DIR}
    - key:
        files:
          - .pre-commit-config.yaml
      paths:
        - ${PRE_COMMIT_HOME}

  before_script:
    - apk add git nodejs
    - python --version --version
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  only:
    - master

pre-commit-changed:
  <<: *pre-commit
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"
  only:
    - merge_requests

smoke:
  cache:
    <<: *global_cache
    key: v1-pip-3.7
  image: python:3.7-alpine
  stage: Test
  before_script:
    - *setup
    - pip install .
  script:
    - latexbuddy --help
  only:
    - master
    - merge_requests

pytest:
  cache:
    <<: *global_cache
    key: v1-pip-$PYTHON_VERSION
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
  image: $CI_REGISTRY/latexbuddy/ci-docker-image:$PYTHON_VERSION
  stage: Test
  needs:
    - smoke
  before_script:
    - python --version --version
    - pip install . tox virtualenv
  script:
    - tox run --skip-missing-interpreters --skip-env docs
  only:
    - master
    - merge_requests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: pytest-junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

########################################################################
#                           RELEASE WORKFLOW                           #
########################################################################

build:
  stage: Build
  cache: {}
  before_script:
    - *setup
    - pip install --upgrade build
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week
  only:
    - master
    - tags

publish:
  stage: Publish
  cache: {}
  needs:
    - build
  before_script:
    - *setup
    - pip install --upgrade twine
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python3 -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags
  dependencies:
    - build

release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - export VERSION=$(printf '%s' "$CI_COMMIT_TAG" | cut -c 2-)
    - sed '/$VERSION/,/^## /!d;//d' CHANGELOG.md > CURRENT_CHANGES.md
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: ./CURRENT_CHANGES.md
