image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

cache:
  - key:
      files:
        - pyproject.toml
        - poetry.lock
    paths:
      - ${PIP_CACHE_DIR}
      - ${POETRY_CACHE_DIR}
  - key:
      files:
        - .pre-commit-config.yaml
    paths:
      - ${PRE_COMMIT_HOME}

stages:
  - Lint
  - Test
  - Build
  - Publish

pre-commit:
  stage: Lint
  before_script:
    - pip install pre-commit
  script:
    - |
      if [[ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]]; then
        git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"
      else
        pre-commit run --all-files
      fi
  only:
    - master
    - merge_requests

.smoke: &smoke_base
  stage: Test
  needs:
    - pre-commit
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run latexbuddy --help
  only:
    - master
    - merge_requests

Smoke test 37/5:
  <<: *smoke_base
  image: python:3.7

Smoke test 38/5:
  <<: *smoke_base
  image: python:3.8

Smoke test 39/5:
  <<: *smoke_base
  image: python:3.9

Smoke test 310/5:
  <<: *smoke_base
  image: python:3.10

Smoke test 311/5:
  <<: *smoke_base
  image: python:3.11

build:
  stage: Build
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week
  only:
    - tags

publish:
  stage: Publish
  needs: 
    - build
  before_script:
    - pip install poetry
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - tags
  dependencies:
    - build
