image: python:latest

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  PIP_CACHE_DIR: "$XDG_CACHE_HOME/pip"
  PRE_COMMIT_HOME: "$XDG_CACHE_HOME/pre-commit"
  SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version

stages:
  - Lint
  - Smoke Test
  - Build
  - Publish

pre-commit: &pre-commit
  stage: Lint
  image: python:alpine
  cache:
    - key: v1-pip
      paths:
        - ${PIP_CACHE_DIR}
    - key:
        files:
          - .pre-commit-config.yaml
      paths:
        - ${PRE_COMMIT_HOME}

  before_script:
    - apk add git build-base
    - python --version --version
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  only:
    - master

pre-commit-changed:
  <<: *pre-commit
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"
  only:
    - merge_requests


.smoke: &smoke_base
  stage: Smoke Test
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry run latexbuddy --help
  only:
    - master
    - merge_requests

smoke-py37:
  <<: *smoke_base
  image: python:3.7

smoke-py311:
  <<: *smoke_base
  image: python:3.11

build:
  stage: Build
  before_script:
    - pip install poetry
  script:
    - poetry install
    - poetry build
  artifacts:
    public: false
    paths:
      - dist/
    expire_in: 1 week
  only:
    - tags

publish:
  stage: Publish
  before_script:
    - pip install poetry
    - poetry config repositories.gitz "https://git.rz.tu-bs.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - poetry publish --repository gitz -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - tags
  dependencies:
    - build
