image: python:alpine

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  PIP_CACHE_DIR: "$XDG_CACHE_HOME/pip"
  PRE_COMMIT_HOME: "$XDG_CACHE_HOME/pre-commit"

default:
  before_script:
    - apk add git
    - python --version --version
    - pip install --upgrade setuptools pip virtualenv
    - virtualenv .venv
    - source .venv/bin/activate

cache:
  - key:
      files:
        - pyproject.toml
        - requirements-dev.txt
    paths:
      - ${PIP_CACHE_DIR}
  - key:
      files:
        - .pre-commit-config.yaml
    paths:
      - ${PRE_COMMIT_HOME}

stages:
  - Lint
  - Test
  - Build
  - Publish

pre-commit: &pre-commit
  stage: Lint
  script:
    - pip install pre-commit
    - pre-commit run --all-files
  only:
    - master

pre-commit-changed:
  <<: *pre-commit
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"
  only:
    - merge_requests

smoke:
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
  image: python:$PYTHON_VERSION-alpine
  stage: Test
  script:
    - pip install .
    - latexbuddy --help
  only:
    - master
    - merge_requests

build:
  stage: Build
  script:
    - pip install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week
  only:
    - tags

publish:
  stage: Publish
  needs:
    - build
  script:
    - pip install --upgrade twine
    - python3 -m twine upload
  only:
    - tags
  dependencies:
    - build
