image: python:alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

cache:
  - key:
      files:
        - pyproject.toml
        - requirements-dev.txt
    paths:
      - ${PIP_CACHE_DIR}
  - key:
      files:
        - .pre-commit-config.yaml
    paths:
      - ${PRE_COMMIT_HOME}

stages:
  - Lint
  - Test
  - Build
  - Publish

pre-commit: &pre-commit
  stage: Lint
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  only:
    - master

pre-commit-changed:
  <<: *pre-commit
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"
  only:
    - merge_requests

.smoke: &smoke_base
  stage: Test
  before_script:
    - pip install .
  script:
    - latexbuddy --help
  only:
    - master
    - merge_requests

Smoke test 37/5:
  <<: *smoke_base
  image: python:3.7

Smoke test 38/5:
  <<: *smoke_base
  image: python:3.8

Smoke test 39/5:
  <<: *smoke_base
  image: python:3.9

Smoke test 310/5:
  <<: *smoke_base
  image: python:3.10

Smoke test 311/5:
  <<: *smoke_base
  image: python:3.11

build:
  stage: Build
  before_script:
    - pip install --upgrade build
  script:
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week
  only:
    - tags

publish:
  stage: Publish
  needs:
    - build
  before_script:
    - pip install --upgrade twine
  script:
    - python3 -m twine upload
  only:
    - tags
  dependencies:
    - build
