image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"

cache:
    paths:
        - .cache/pip

before_script:
    - python --version

stages:
    - Lint
    - Smoke Test
    - Build

isort:
    stage: Lint
    script:
        - pip install isort
        - isort --check --diff "$SRC_DIR"
    only:
        - master
        - merge_requests

black:
    stage: Lint
    script:
        - pip install black
        - black --check --diff "$SRC_DIR"
    only:
        - master
        - merge_requests

.smoke: &smoke_base
    stage: Smoke Test
    before_script:
        - pip install poetry
    script:
        - poetry install
        - poetry run latexbuddy --help
    only:
        - master
        - merge_requests

smoke-py36:
  <<: *smoke_base
  image: python:3.6

smoke-py39:
  <<: *smoke_base
  image: python:3.9

build:
    stage: Build
    before_script:
        - pip install poetry
    script:
        - poetry install
        - poetry build
    artifacts:
        public: false
        paths:
            - dist/
        expire_in: 1 month
    only:
        - tags
