image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"

cache:
    paths:
        - .cache/pip

before_script:
    - python --version

stages:
    - Lint

isort:
    stage: Lint
    script:
        - pip install isort
        - isort --check --diff "$SRC_DIR"

black:
    stage: Lint
    script:
        - pip install black
        - black --check --diff "$SRC_DIR"
