image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    SRC_DIR: "$CI_PROJECT_DIR/latexbuddy"

cache:
    paths:
        - .cache/pip

before_script:
    - python --version

stages:
    - Lint
    - Smoke Test

isort:
    stage: Lint
    script:
        - pip install isort
        - isort --check --diff "$SRC_DIR"
    only:
        - master
        - merge_requests

black:
    stage: Lint
    script:
        - pip install black
        - black --check --diff "$SRC_DIR"
    only:
        - master
        - merge_requests

.smoke: &smoke_base
    stage: Smoke Test
    before_script:
        - pip install poetry
    script:
        - poetry export -o requirements.txt
        - pip install -r requirements.txt
        - python -m compileall ./latexbuddy/
    only:
        - master
        - merge_requests

smoke-py36:
  <<: *smoke_base
  image: python:3.6

smoke-py39:
  <<: *smoke_base
  image: python:3.9

