# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
      - id: name-tests-test
        args: [--pytest]
        files: ^tests/unit/ # TODO: change after all tests get renamed
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]
        exclude: ^latexbuddy/config_loader.py$
      - id: reorder-python-imports
        args: [--py37-plus]
        files: ^latexbuddy/config_loader.py$
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies:
          - tomli
        args:
          - "--in-place"
          - "--config"
          - "./pyproject.toml"
  # TODO: replace with yamlfmt, mdformat, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^latexbuddy/templates/
        exclude_types:
          - jinja
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.9"
    hooks:
      - id: ruff
        files: ^latexbuddy/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --no-warn-unused-ignores
          - --allow-redefinition
          - --check-untyped-defs
          - --disallow-any-generics
          - --disallow-incomplete-defs
          - --disallow-untyped-defs
          - --warn-redundant-casts
        additional_dependencies:
          - types-chardet
          - types-colorama
          - types-requests
        files: ^latexbuddy/
