# See https://pre-commit.com for more information
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-ast
          - id: check-builtin-literals
          - id: check-docstring-first
          - id: debug-statements
          - id: fix-encoding-pragma
            args: [--remove]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.3.0
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
            exclude: ^latexbuddy/templates/.*\.html$
            exclude_types:
                - jinja
