version: 2

python:
  install:
    - requirements: docs/requirements.txt

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  jobs:
    post_create_environment:
      # Install hatch
      - pip install hatch
      # Export requirements for the docs
      - hatch -e docs dep show requirements >! docs/requirements.txt

formats:
  - epub
  - pdf
