version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "3"
    jobs:
        post_create_environment:
            # Install poetry
            - pip install poetry
            # Tell poetry to not use a virtual environment
            - poetry config virtualenvs.create false
            # Install dependencies with 'docs' dependency group
            - poetry install --with docs

formats:
    - epub
    - pdf
