[tool.poetry]
name = "latexbuddy"
version = "0.4.2"
description = ""
license = "Proprietary"
authors = [
    "Niklas Pieninck <n.pieninck@tu-braunschweig.de>",
    "Levi Elsner <levi.elsner@tu-braunschweig.de>",
    "Paul Franke <paul.franke@tu-braunschweig.de>",
    "Jana Haupt <jana.haupt@tu-braunschweig.de>",
    "Hendrik Hentschel <h.hentschel@tu-braunschweig.de>",
    "Nikita Karamov <me@kytta.dev>",
    "Lennart Lutz <l.lutz@tu-braunschweig.de>",
    "David Meyer <da.meyer@tu-braunschweig.de>",
    "Paul Nowitzki <p.nowitzki@tu-braunschweig.de>",
    "Maik Weber <maik.weber@tu-braunschweig.de>"
]
readme = "README.md"
include = ["CHANGELOG.md", "NOTICE"]

[tool.poetry.dependencies]
python = "^3.7.15"
requests = "^2.28.1"
Jinja2 = "^3.0.1"
yalafi = "^1.4.0"
chardet = "^5.0.0"
proselint = "~0.11.3"
Unidecode = "^1.2.0"
colorama = { version = "^0.4.6", markers = "sys_platform == 'win32'"}
pydantic = "^1.10.2"
bibtexparser = "^1.4.0"
Flask = "^2.0.1"
PyLaTeX = "^1.4.1"
platformdirs = "^2.6.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"


[tool.poetry.group.docs.dependencies]
sphinx = "^5.3.0"
myst-parser = "~0.18.1"
furo = "2022.12.7"
readthedocs-sphinx-search = "~0.1.2"
sphinx-autobuild = "^2021.3.14"
sphinx-argparse = "~0.4.0"


[tool.poetry.scripts]
latexbuddy = "latexbuddy.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
ignore = ["W503"]
