[tool.poetry]
name = "latexbuddy"
version = "0.0.0"
description = ""
license = "Proprietary"
authors = [
    "Nikita Karamov <n.karamov@tu-braunschweig.de>"
]
readme = "README.md"
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"

[tool.poetry.scripts]
latexbuddy = "latexbuddy.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
exclude = '/(\.git | dist)/'

[tool.isort]
profile = "black"
known_first_party = "latexbuddy"
src_paths = ["latexbuddy", "tests"]
atomic = true
lines_after_imports = 2
lines_between_types = 1
